version: '3'

services:
  django:
    build:
      dockerfile: ./docker/gwlab_viterbi_django.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlab_viterbi_django:0.13
    container_name: gwlab_viterbi_django
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: gwlab_viterbi
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_HOST: db
    ports:
      - "8000"
    depends_on:
      - db

  nginx:
    build:
      dockerfile: ./docker/gwlab_viterbi_nginx.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlab_viterbi_nginx:0.1
    container_name: gwlab_viterbi_nginx
    ports:
      - "8000:8000"
    depends_on:
      - static
      - django
      
  static:
    build:
      dockerfile: ./docker/gwlab_viterbi_static.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlab_viterbi_static:0.12
    container_name: gwlab_viterbi_static
    ports:
      - "8000"
      
  db:
    image: mysql:5.7
    container_name: gwlab_viterbi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: gwlab_viterbi
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
    volumes:
      - var_lib_mysql:/var/lib/mysql
  
volumes:
  var_lib_mysql:
