---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwlab-viterbi-django
  namespace: gwcloud
  labels:
    name: gwlab-viterbi-django
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwlab-viterbi-django
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwlab-viterbi-django
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: viterbi
            - secretRef:
                name: common
          name: gwlab-viterbi-django
          image: nexus.gwdc.org.au/docker/gwlab_viterbi_django:0.2
          ports:
            - name: http
              containerPort: 8000
          resources: {}
          tty: true
      imagePullSecrets:
      - name: regcred
... 
