apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: viterbi
  name: secrets-integrator-viterbi
  namespace: gwcloud
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-init-first: 'true'
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-secret-viterbi.yaml: kv/gwcloud/viterbi
            vault.hashicorp.com/agent-inject-template-viterbi.yaml: |
              {{- with secret "kv/gwcloud/viterbi" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              stringData:
                {{ range $k, $v := .Data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: gwcloud
                name: viterbi
              {{- end }}
            vault.hashicorp.com/agent-pre-populate-only: 'true'
            vault.hashicorp.com/role: viterbi
        spec:
          containers:
            - command:
                - kubectl
                - apply
                - '-f'
                - /vault/secrets/
              image: 'bitnami/kubectl:1.17.4'
              imagePullPolicy: IfNotPresent
              name: viterbi-vault-kube-integrator
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: viterbi
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
