apiVersion: v1
kind: Service
metadata:
  labels:
    name: gwlab-viterbi-nginx
  name: gwlab-viterbi-nginx
  namespace: gwcloud
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: gwlab-viterbi-nginx
  sessionAffinity: None
  type: ClusterIP
