# Generated by Django 2.2.16 on 2020-11-12 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_choice', models.CharField(choices=[['simulated', 'Simulated'], ['real', 'Real']], default='real', max_length=55)),
                ('source_dataset', models.CharField(blank=True, choices=[['o1', 'O1'], ['o2', 'O2']], default='o1', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ViterbiJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('labels', models.ManyToManyField(to='viterbi.Label')),
            ],
            options={
                'unique_together': {('user_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SearchParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_parameter', to='viterbi.ViterbiJob')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='viterbi.Search')),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='viterbi.ViterbiJob'),
        ),
        migrations.CreateModel(
            name='DataParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='viterbi.Data')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_parameter', to='viterbi.ViterbiJob')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='viterbi.ViterbiJob'),
        ),
    ]
