# Generated by Django 2.2.16 on 2021-03-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viterbi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viterbijob',
            name='is_ligo_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='source_dataset',
            field=models.CharField(blank=True, choices=[['o1', 'O1'], ['o2', 'O2'], ['o3', 'O3']], default='o1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='viterbi.Data'),
        ),
        migrations.AlterField(
            model_name='searchparameter',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='viterbi.Search'),
        ),
    ]
