# Generated by Django 2.2.16 on 2021-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viterbi', '0002_auto_20210322_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viterbijob',
            name='is_ligo_job',
            field=models.BooleanField(default=False),
        ),
    ]
