# Generated by Django 2.2.16 on 2021-06-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viterbi', '0003_auto_20210322_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viterbijob',
            old_name='job_id',
            new_name='job_controller_id',
        ),
    ]
