# Generated by Django 2.2.16 on 2022-04-14 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viterbi', '0004_auto_20210608_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownloadToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('path', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viterbi.ViterbiJob')),
            ],
        ),
    ]
