# Generated by Django 3.2.13 on 2022-07-01 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viterbi', '0005_filedownloadtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViterbiSummaryResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_data', models.TextField()),
                ('table_data', models.TextField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_results', to='viterbi.viterbijob')),
            ],
        ),
    ]
